#!/usr/bin/env bash
# Script for querying domain names based on domains and subdomains

query_dns() {
    local subdomain="$2"
    local domain="$1"

    local dns_output=$(dig ${subdomain}.${domain} +short)

    local record_type=$(echo "${dns_output}" | awk '{if (NR==1) {if ($1 == ";;") print "NO_RECORD"; else if ($4 == "CNAME") print "CNAME"; else print "A"}}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${dns_output}"
}

if [ $# == 1 ]; then
    query_dns "www" "${domain}"
    query_dns "lb-01" "${domain}"
    query_dns "web-01" "${domain}"
    query_dns "web-02" "${domain}"
else
    query_dns "${1}" "${2}"
fi
