#!/usr/bin/env bash
# Script for querying domain names based on domains and subdomains

query_dns() {
    local subdomain="$2"
    local domain="$1"

    local dns_output=$(dig ${subdomain}.${domain} +short)

    local record_type=$(echo "${dns_output}" | awk '{if (NR==1) {if ($1 == ";;") print "NO_RECORD"; else if ($4 == "CNAME") print "CNAME"; else print "A"}}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${dns_output}"
}

if [ $# -eq 1 ]; then
    domain="$1"
    query_dns "${domain}" "www"
    query_dns "${domain}" "lb-01"
    query_dns "${domain}" "web-01"
    query_dns "${domain}" "web-02"
else
    query_dns "${1}" "${2}"
fi
