#!/usr/bin/env bash
# Configures a new Ubuntu machine to include a custom HTTP header in Nginx responses

sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i '/server {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
