#!/usr/bin/env bash
# debugging what is going on with a ubuntu container's Nginx installation

sudo apt-get update
sudo apt-get install -y nginx


cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF


sudo service nginx restart
